<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SC3</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b939dd0b-429b-49a2-8670-75076f1683b2</testSuiteGuid>
   <testCaseLink>
      <guid>611a45d8-90f4-41be-aa22-a310947061c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 3</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>de4cd396-adcf-41ec-bec7-42a1ddece33c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/NewData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>de4cd396-adcf-41ec-bec7-42a1ddece33c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>f7757e97-b71f-417f-8005-75443ae3da66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>de4cd396-adcf-41ec-bec7-42a1ddece33c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>7429cb91-50d0-4bc6-8cf9-05e306ed6ae3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
